## Deteksi Emosi Pengguna Twitter

Deteksi emosi merupakan salah satu permasalahan yang dihadapi pada ***Natural Language Processing*** (NLP). Alasanya diantaranya adalah kurangnya dataset berlabel untuk mengklasifikasikan emosi berdasarkan data twitter. Selain itu, sifat dari data twitter yang dapat memiliki banyak label emosi (***multi-class***). Manusia memiliki berbagai emosi dan sulit untuk mengumpulkan data yang cukup untuk setiap emosi. Oleh karena itu, masalah ketidakseimbangan kelas akan muncul (***class imbalance***). Pada Ujian Tengah Semester (UTS) kali ini, Anda telah disediakan dataset teks twitter yang sudah memiliki label untuk beberapa kelas emosi. Tugas utama Anda adalah membuat model yang mumpuni untuk kebutuhan klasifikasi emosi berdasarkan teks.

### Informasi Data

Dataset yang akan digunakan adalah ****tweet_emotion.csv***. Berikut merupakan informasi tentang dataset yang dapat membantu Anda.

- Total data: 40000 data
- Label emosi: anger, boredom, empty, enthusiasm, fun, happiness, hate, love, neutral, relief, sadness, surprise, worry
- Jumlah data untuk setiap label tidak sama (***class imbalance***)
- Terdapat 3 kolom = 'tweet_id', 'sentiment', 'content'

### Penilaian UTS

UTS akan dinilai berdasaarkan 4 proses yang akan Anda lakukan, yaitu pra pengolahan data, ektraksi fitur, pembuatan model machine learning, dan evaluasi.

#### Pra Pengolahan Data

> **Perhatian**
> 
> Sebelum Anda melakukan sesuatu terhadap data Anda, pastikan data yang Anda miliki sudah "baik", bebas dari data yang hilang, menggunakan tipe data yang sesuai, dan sebagainya.
>

Data tweeter yang ada dapatkan merupakan sebuah data mentah, maka beberapa hal dapat Anda lakukan (namun tidak terbatas pada) yaitu,

1. Case Folding
2. Tokenizing
3. Filtering
4. Stemming


*CATATAN: PADA DATA TWITTER TERDAPAT *MENTION* (@something) YANG ANDA HARUS TANGANI SEBELUM MASUK KE TAHAP EKSTRAKSI FITUR*

#### Ekstrasi Fitur

Anda dapat menggunakan beberapa metode, diantaranya

1. Bag of Words (Count / TF-IDF)
2. N-gram
3. dan sebagainya

#### Pembuatan Model

Anda dibebaskan dalam memilih algoritma klasifikasi. Anda dapat menggunakan algoritma yang telah diajarkan didalam kelas atau yang lain, namun dengan catatan. Berdasarkan asas akuntabilitas pada pengembangan model machine learning, Anda harus dapat menjelaskan bagaimana model Anda dapat menghasilkan nilai tertentu.

#### Evaluasi

Pada proses evaluasi, minimal Anda harus menggunakan metric akurasi. Akan tetapi Anda juga dapat menambahkan metric lain seperti Recall, Precision, F1-Score, detail Confussion Metric, ataupun Area Under Curve (AUC).

### Lembar Pengerjaan
Lembar pengerjaan dimulai dari cell dibawah ini

In [500]:
import numpy as np
import pandas as pd
import re

import nltk
nltk.download('wordnet')
from nltk.corpus import stopwords

import spacy


from scipy.stats import itemfreq
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,HashingVectorizer
from sklearn.metrics import confusion_matrix

pd.options.mode.chained_assignment = None


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\fashf\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [501]:
df = pd.read_csv('data/tweet_emotions.csv')

df.head(10)

tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...
5  1956968477       worry  Re-pinging @ghostridah14: why didn't you go to...
6  1956968487     sadness  I should be sleep, but im not! thinking about ...
7  1956968636       worry               Hmmm. http://www.djhero.com/ is down
8  1956969035     sadness            @charviray Charlene my love. I miss you
9  1956969172     sadness         @kelcouch I'm sorry  at least it's Friday?

In [502]:
df.shape

(40000, 3)

In [503]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   tweet_id   40000 non-null  int64 
 1   sentiment  40000 non-null  object
 2   content    40000 non-null  object
dtypes: int64(1), object(2)
memory usage: 937.6+ KB


In [504]:
df = df[['tweet_id', 'sentiment', 'content']].copy()

In [505]:
df.sentiment.value_counts()

neutral       8638
worry         8459
happiness     5209
sadness       5165
love          3842
surprise      2187
fun           1776
relief        1526
hate          1323
empty          827
enthusiasm     759
boredom        179
anger          110
Name: sentiment, dtype: int64

In [506]:
df.sentiment = np.where((df.sentiment == 'neutral') | (df.sentiment == 'empty') | (df.sentiment == 'boredom'), 'neutral', df.sentiment)

In [507]:
df.sentiment = np.where((df.sentiment == 'fun') | (df.sentiment == 'enthusiasm'), 'fun', df.sentiment)

In [508]:
df = df[df.sentiment != 'neutral']

In [509]:
df.sentiment.value_counts()

worry        8459
happiness    5209
sadness      5165
love         3842
fun          2535
surprise     2187
relief       1526
hate         1323
anger         110
Name: sentiment, dtype: int64

In [510]:
df2 = pd.read_csv('data/tweets_clean.txt',sep='	', header=None)

In [511]:
df2.head(10)

0                                                  1  \
0  145353048817012736:  Thinks that @melbahughes had a great 50th birt...   
1  144279638024257536:  Como una expresión tan simple, una sola oració...   
2  140499585285111809:  the moment when you get another follower and y...   
3  145207578270507009:  Be the greatest dancer of your life! practice ...   
4  139502146390470656:  eww.. my moms starting to make her annual rum ...   
5  146042696899887106:  If ur heart hurts all the time for tht person ...   
6  145492569609084928:  I feel awful, and it's way too freaking early....   
7  145903955229151232:  So chuffed for safc fans! Bet me dar comes in ...   
8  142717613234069504:  Making art and viewing art are different at th...   
9  144183822873927680:  Soooo dooowwwn!! Move on, get some sleep... Me...   

             2  
0  :: surprise  
1   :: sadness  
2       :: joy  
3       :: joy  
4   :: disgust  
5       :: joy  
6       :: joy  
7       :: joy  
8      :: fear  
9     :: anger

In [512]:
df2.columns=['tweet_id','content','sentiment']

In [513]:
df2.sentiment = df2.sentiment.str.replace(':: ','')

In [514]:
df2.sentiment.value_counts()

joy         8240
surprise    3849
sadness     3830
fear        2816
anger       1555
disgust      761
Name: sentiment, dtype: int64

##### Emotions to keep

##### worry,happpy(happiness,joy),surprise,sadness,love,fear,anger,hate(disgust+hate),relief,fun(fun+enthusiasm)

In [515]:
data = df.append(df2)
data.head(10)

tweet_id sentiment                                            content
1   1956967666   sadness  Layin n bed with a headache  ughhhh...waitin o...
2   1956967696   sadness                Funeral ceremony...gloomy friday...
3   1956967789       fun               wants to hang out with friends SOON!
5   1956968477     worry  Re-pinging @ghostridah14: why didn't you go to...
6   1956968487   sadness  I should be sleep, but im not! thinking about ...
7   1956968636     worry               Hmmm. http://www.djhero.com/ is down
8   1956969035   sadness            @charviray Charlene my love. I miss you
9   1956969172   sadness         @kelcouch I'm sorry  at least it's Friday?
11  1956969531     worry                            Choked on her retainers
12  1956970047   sadness  Ugh! I have to beat this stupid song to get to...

In [516]:
data.sentiment = np.where((data.sentiment == 'disgust') |(data.sentiment == 'hate'),'hate',data.sentiment)

In [517]:
data=data[data.sentiment.isin(['sadness','worry','joy'])]

In [518]:
data.sentiment.value_counts()

sadness    8995
worry      8459
joy        8240
Name: sentiment, dtype: int64

### Membersihkan Teks

##### Hapus karakter yang tidak relevan selain alfanumerik dan spasi

In [519]:
data['content']=data['content'].str.replace('[^A-Za-z0-9\s]+', '')

<ipython-input-519-8e58614b0d91>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data['content']=data['content'].str.replace('[^A-Za-z0-9\s]+', '')


##### Hapus tautan dari teks

In [520]:
data['content']=data['content'].str.replace('http\S+|www.\S+', '', case=False)

<ipython-input-520-a260812f61fd>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data['content']=data['content'].str.replace('http\S+|www.\S+', '', case=False)


##### Ubah semuanya menjadi huruf kecil

In [521]:
data['content']=data['content'].str.lower()

##### Tetapkan Variabel Target

In [522]:
target=data.sentiment
data = data.drop(['sentiment'],axis=1)

In [523]:
le=LabelEncoder()
target=le.fit_transform(target)

### Split Data kedalam train & test

In [524]:
X_train, X_test, y_train, y_test = train_test_split(data,target,stratify=target,test_size=0.4, random_state=42)

##### Periksa apakah split membagi kelas secara seragam

In [525]:
itemfreq(y_train)

<ipython-input-525-01f9992843c9>:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  itemfreq(y_train)


array([[   0, 4944],
       [   1, 5397],
       [   2, 5075]], dtype=int64)

In [526]:
itemfreq(y_test)

<ipython-input-526-07c65b4fa6f5>:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  itemfreq(y_test)


array([[   0, 3296],
       [   1, 3598],
       [   2, 3384]], dtype=int64)

## Tokenization
##### Tokenization dapat dilakukan dengan berbagai cara, yaitu **Bag of words, tf-idf, Glove, word2vec ,fasttext** etc. Sekarang lakukan penerapannya dan pengaruhnya terhadap akurasi

##### **Bag of Words**

In [527]:
# Extract fitur
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train.content)
X_test_counts =count_vect.transform(X_test.content)
print('Shape of Term Frequency Matrix: ',X_train_counts.shape)

Shape of Term Frequency Matrix:  (15416, 25747)


1. **Naive Bayess Model**

In [528]:
# Training Naive Bayes (NB) menggunakan training data.
clf = MultinomialNB().fit(X_train_counts,y_train)
predicted = clf.predict(X_test_counts)
nb_clf_accuracy = np.mean(predicted == y_test) * 100
print(nb_clf_accuracy)

59.26250243237984


2. **Menggunakan Pipeline**
   * tentukan fungsi untuk akurasi pencetakan

In [529]:
def print_acc(model):
    predicted = model.predict(X_test.content)
    accuracy = np.mean(predicted == y_test) * 100
    print(accuracy)

In [530]:
nb_clf = Pipeline([('vect', CountVectorizer()), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

59.26250243237984


3. **TF IDF transformer**

In [531]:
nb_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

58.54251799961082


4. **Hash Vectorizer**
   * Naive Bayes membutuhkan input non-negatif. Oleh karena itu, tanda alternatif harus disetel ke false di Hashing Vectorizer untuk membuatnya bekerja dengan algoritma naive bayes

In [532]:
nb_clf = Pipeline([('vect', HashingVectorizer(n_features=2500,alternate_sign=False)), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

53.76532399299475


In [533]:
confusion_matrix(y_test,predicted)

array([[2430,  517,  349],
       [ 551, 1989, 1058],
       [ 434, 1278, 1672]], dtype=int64)

5. **Hapus Stop Words**

In [534]:
stop_words = set(stopwords.words('english'))
nb_clf = Pipeline([('vect', CountVectorizer(stop_words=stop_words)), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

58.23117338003503


In [535]:
nb_clf = Pipeline([('vect', CountVectorizer(stop_words=stop_words)), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

57.60848414088344


6. **Lemmatization**

In [536]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatize_text(text):
    return ' '.join([lemmatizer.lemmatize(w) for w in w_tokenizer.tokenize(text)])
X_train.loc[:,'content'] = X_train['content'].apply(lemmatize_text)
X_test.loc[:,'content'] = X_test['content'].apply(lemmatize_text)

In [537]:
nb_clf = Pipeline([('vect', CountVectorizer(stop_words=stop_words)), ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])
nb_clf = nb_clf.fit(X_train.content,y_train)
print_acc(nb_clf)

57.41389375364857
